---
name: 'lydteamet-helm-pull-action'
description: 'Pulls a helm chart from azurecr'
inputs:
  name:
    description: Name of chart
    required: true

  version:
    description: Chart semantic version
    required: true

  repository:
    description: Repository name for the chart 
    required: true

  registry:
    description: Registry to push to
    required: true
    default: plattform.azurecr.io

  username:
    description: Username for registry
    required: true

  password:
    description: Password for registry
    required: true

  github_token:
    description: Github token passed along
    required: true

runs:
  using: 'composite'
  steps:

    - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0
    
    - name: Login to registry
      shell: bash
      run:  |
        export HELM_EXPERIMENTAL_OCI=1
        echo ${{ inputs.password }} | helm registry login -u ${{ inputs.username }} --password-stdin ${{ inputs.registry }}

    - name: Pull chart
      shell: bash
      run: |
        export HELM_EXPERIMENTAL_OCI=1
        helm pull oci://${{ inputs.registry }}/${{ inputs.repository }}/${{ inputs.name }} --version ${{ inputs.version }}
